# ==========================================================================

# --------------------------------------------------------------------------






# ==========================================================================

# --------------------------------------------------------------------------

# --------------------------------------------------------------------------

#
#   Execution failed for task ':aidl:compileDebugAidl'.
#     > java.nio.charset.MalformedInputException: Input length = 1
#       at com.android.builder.internal.incremental.DependencyData
#            .processDependencyData(DependencyData.java:118)
#       at com.android.build.gradle.tasks.AidlCompile$DepFileProcessor
#            .processFile(AidlCompile.kt:116)
#








#


#


# --------------------------------------------------------------------------

org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.enableR8.fullMode=true
android.overridePathCheck=true



android.suppressUnsupportedCompileSdk=37
