pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        
        
        maven {
            url 'https://jitpack.io'
            content {
                includeGroup 'com.github.topjohnwu.libsu'
                includeGroup 'com.github.Kyant0'
                includeGroup 'com.github.jeziellago'
            }
        }
    }

    // ==========================================================================
    
    // --------------------------------------------------------------------------
    
    
    
    
    //
    
    
    // ==========================================================================
    versionCatalogs {
        serverLibs {
            from(files('embedded/server/server.versions.toml'))
        }
        apiLibs {
            from(files('embedded/api/api.versions.toml'))
        }
        managerLibs {
            from(files('embedded/manager/manager.versions.toml'))
        }

        libs {
            version('hidden-api', '4.4.0')
            library('hidden-compat', 'dev.rikka.hidden', 'compat').versionRef('hidden-api')
            library('hidden-stub', 'dev.rikka.hidden', 'stub').versionRef('hidden-api')

            version('refine', '4.4.0')
            library('refine-runtime', 'dev.rikka.tools.refine', 'runtime').versionRef('refine')
            library('refine-annotation', 'dev.rikka.tools.refine', 'annotation').versionRef('refine')
            library('refine-annotation-processor', 'dev.rikka.tools.refine', 'annotation-processor').versionRef('refine')
        }
    }
}

rootProject.name = "YouLongTool"
include ':app'

// ==========================================================================

// --------------------------------------------------------------------------

//       https://github.com/roro2239/Stellar-API    (MPL-2.0 + Apache-2.0)
//



//










//



// ==========================================================================
include ':manager'
include ':server'
include ':api'
include ':provider'
include ':aidl'
include ':shared'
include ':userservice'
include ':shizuku-aidl'
include ':shizuku-api'

project(':manager').projectDir = file('embedded/manager')
project(':server').projectDir = file('embedded/server')
project(':api').projectDir = file('embedded/api')
project(':provider').projectDir = file('embedded/provider')
project(':aidl').projectDir = file('embedded/aidl')
project(':shared').projectDir = file('embedded/shared')
project(':userservice').projectDir = file('embedded/userservice')
project(':shizuku-aidl').projectDir = file('embedded/shizuku-aidl')
project(':shizuku-api').projectDir = file('embedded/shizuku-api')
