// ==========================================================================

// --------------------------------------------------------------------------

//


//




//



//





//




//




//          Failed to apply plugin 'dev.rikka.tools.autoresconfig'.
//          > Android application extension not found



//







//


//


//






//







// ==========================================================================

plugins {
    id('com.android.library')
    id('org.jetbrains.kotlin.android')
    id('org.jetbrains.kotlin.plugin.compose')
    id('com.google.devtools.ksp')
    id('dev.rikka.tools.refine')
}

android {
    namespace 'roro.stellar.manager'

    defaultConfig {
        
        
        
        
        
        
        //        Unresolved reference 'VERSION_CODE' / 'VERSION_NAME'
        
        
        buildConfigField 'int', 'VERSION_CODE', "${rootProject.ext.versionCode}"
        buildConfigField 'String', 'VERSION_NAME', "\"${rootProject.ext.versionName}\""
    }

    buildFeatures {
        buildConfig true
        compose true
    }

    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'proguard-rules.pro'
        }
    }

    packagingOptions {
        resources {
            excludes += ['/META-INF/**']
        }
    }

    kotlin {
        jvmToolchain(21)
    }
}

configurations.configureEach {
    exclude group: 'androidx.profileinstaller', module: 'profileinstaller'
}

dependencies {
    implementation managerLibs.bundles.kotlinxCoroutines

    implementation project(':server')
    implementation project(':api')
    implementation project(':provider')

    implementation libs.hidden.compat
    compileOnly libs.hidden.stub

    implementation managerLibs.bundles.core
    implementation managerLibs.bundles.lifecycle

    implementation managerLibs.material

    def composeBom = platform(managerLibs.composeBom)
    implementation composeBom
    implementation managerLibs.bundles.composeUi
    debugImplementation managerLibs.composeUiTooling

    implementation managerLibs.libsuCore

    implementation managerLibs.bundles.nativeCrypto

    implementation managerLibs.appiconloader

    implementation managerLibs.okhttp

    implementation managerLibs.capsule

    implementation managerLibs.composeMarkdown

    implementation managerLibs.roomRuntime
    implementation managerLibs.roomKtx
    ksp managerLibs.roomCompiler
    implementation managerLibs.gson
    implementation managerLibs.workRuntimeKtx
}
